### ISSUE TITLE
Using as part of a stream?

### ISSUE THREAD

**Issue by FurnitureFun** [Tremeschin/ModularMusicVisualizer#7]
Is it possible to run this code as part of an audio stream in "real time"?

Ideally I'd like to have a setup where there's some kind of text to speech engine that renders a soundwave as it speaks.

Something like `gTTS -> MMV -> OBS`?

**Comment by Tremeschin** [comment]
My experience with getting audio input from the system and using within Python is pretty poor in the past, it won't be hard to make it to keep piping the output to somewhere though, will code this right now and I get back to you in a few ~ (piping the video to FFplay, note that this will still require an audio file on the start, will try audio streaming later on as I can see quite a few immediate problems with doing so).

I guarantee you that real time speeds won't be a thing sadly (at least for 1080p, mayybe 480p can work and only with static background images) for the current implementation of it on the main MMVSkia part of the code, Python loops are a bit too slow for this task and also the quad audio processing makes the digital signal processing of it about 70 frames per second max at 2048 batch size of the slices... (because I calculate FFT for the original signal on left and right and also down sample the audio, calculate the FFT again for getting extra info on the bass frequencies).

In the medium / long term future I hope I can use GLSL shaders for generating the videos, actually I'm just toying with this on a separate branch called `namespace-shady` but that still have some problems I have to sort out, namely how to inject huge amounts of data on a shader and getting a cross platform solution..

It's definitely something I want but it's not really trivial how to implement just yet.

**Comment by Tremeschin** [comment]
Can you clone the other branch:

- `git clone https://github.com/Tremeschin/modular-music-visualizer -b namespace-shady`

Executing `python base_video.py` should create a window and show the final generated frames process while it's happening (it won't render to a video file, only show).

Take your conclusions on the speeds as I warned you :p

<hr>

If you're on Linux you can install the Golang programming language from your distro (and probably the mesa packages for a EGL implementation hard runtime dependency which I'm trying to get rid of, prob won't work on NVIDIA GPUs), edit the file `/src/mmv/test_shady.py`, put a valid image path on the line 41 where it says:

```python
layer2.add_mapping(name = "image", map_type = "image", path = f"{THIS_DIR}/../assets/tremx_assets/secret-image.png")
```

Then execute that `test_shady.py` file, just a sneak peek on what it can be in the future lol

**Comment by Tremeschin** [comment]
Hey great news about this, looks like I can use Python itself to send some info on a pipeline to a shader as well as rendering into separate layers, buffers thanks due `moderngl` package.

For this issue (apart from remaking the whole MMV's code into a GLSL file) will just be about reading audio real time from somewhere!!

I'm making slow progress towards this but if things go well hopefully in a few weeks or months I have some sorta proof of concept going on.

**Comment by FurnitureFun** [comment]
That's amazing, thanks!

**Comment by unfa** [comment]
Wow! I wonder if this could be used with OBS and JACK.
Right now I'm using a plug-in for OBS, but maybe this could be a better solution?

**Comment by Tremeschin** [comment]
> Wow! I wonder if this could be used with OBS and JACK.
> Right now I'm using a plug-in for OBS, but maybe this could be a better solution?

Hey @unfa ! finally the senpai noticed /s

I was just reworking some audio processing code in Python so I can have options on the audio being sourced with a file or from a loopback / monitor device.

I'll try lurking for some Jack Audio package to do that but I can say in advance it probably won't be perfectly synced when real time streaming unless we delay the audio by a couple hundred milisseconds with a lv2 plugin relative to the audio we hear.. So jack is a win here.

I'm quite far from writing MMV as a GLSL shader, what basically makes it possible to render real time because the "old" code by no means has fast enough rendering using Skia graphics library by quite a few reasons.

So far I can create a OpenGL window which acts like a display for the stuff the GPU is rendering at full speed. And that is basically rewriting the project with a new technology to get the graphics PLUS me implementing on a low level code stuff I am used to just .resize(), .blur(), draw lines..

It's something I'm very passionate about lately (CGI from raw math to images) and I really hope I manage to understand the implementation and write such code in the medium term future, it's basically the core of a video editor but controlled by code.

I'll be really busy with IRL for the next 2 weeks or so but I'm very happy with your support right before a short break!! :)

Sorta big write saying out loud the state of the project and this issue is currently my main goal. Thanks, my fear of no one using the project was gone lol

**Comment by Tremeschin** [comment]
Hey people see commit 352567499dbeb27306ea0db7a8c8572f4534cc13 already on master branch :)

Run file `python ./src/mmv/test_mgl.py`, I have only tested with PulseAudio as plugin running JackAudio backend, haven't tested on Windows nor tried a way of making a specific Jack client for Python.

If performance is bad try changing `batch_size = 2048 * 2` to 2048 or even 1024, but it'll reduce precision on the music bars, also my CPU can only do about 80 FPS without getting behind, there is room for improvement tho.

Currently the test number 4 is set which are the music bars directly from a FFT with some basic coloring. Its amplitude also comes from the audio volume so increase it accordingly, will maybe add a GUI for controlling those on the go later on!

**Comment by Tremeschin** [comment]
Hey @FurnitureFun, just commited demo / test code for music bars mode with glsl, it's.. usable as of right now I guess. Just change the target background and logo on the file `test_mgl.py` and you should have a basic hard coded setup.

There probably will be audio delays, set your buffer size to 2048 or something, I still need to sort out some common issues regarding audio recording and also write the interface to write the shaders with a script or config file.

**Comment by FurnitureFun** [comment]
Really sorry, I've been out of the loop for so many reasons, I'll give this a go when I get a chance but given it could be quite a while I'll close this off for now.
